==========================================
SLURM_JOB_ID = 8584778
SLURM_SUBMIT_DIR = /project/kh_mercury_1
SLURM_JOB_NODELIST = mcn53
==========================================
Job ID: 8584778
Job User: pspahwa
Num Cores: 16
Traceback (most recent call last):
  File "/apps/python/3.6/3.6.12/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'FullText'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "updatedDirectSearch.py", line 35, in <module>
    main()
  File "updatedDirectSearch.py", line 28, in main
    news_df["Counts"] = news_df["FullText"].apply(lambda x: find_firms_associated_with_news(x, all_company_lists), meta = "str")
  File "/home/pspahwa/.local/lib/python3.6/site-packages/dask/dataframe/core.py", line 3679, in __getitem__
    meta = self._meta[_extract_meta(key)]
  File "/apps/python/3.6/3.6.12/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/apps/python/3.6/3.6.12/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'FullText'
srun: error: mcn53: task 0: Exited with exit code 1
