==========================================
SLURM_JOB_ID = 8585166
SLURM_SUBMIT_DIR = /project/kh_mercury_1
SLURM_JOB_NODELIST = mcn53
==========================================
Job ID: 8585166
Job User: pspahwa
Num Cores: 16
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 8585166.0 ON mcn53 CANCELLED AT 2021-11-30T00:36:19 ***
slurmstepd: error: *** JOB 8585166 ON mcn53 CANCELLED AT 2021-11-30T00:36:19 ***
Process SpawnPoolWorker-30:
Traceback (most recent call last):
  File "/apps/python/3.6/3.6.12/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/apps/python/3.6/3.6.12/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/apps/python/3.6/3.6.12/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/apps/python/3.6/3.6.12/lib/python3.6/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/apps/python/3.6/3.6.12/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/python/3.6/3.6.12/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/apps/python/3.6/3.6.12/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/python/3.6/3.6.12/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/apps/python/3.6/3.6.12/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/apps/python/3.6/3.6.12/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/apps/python/3.6/3.6.12/lib/python3.6/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/apps/python/3.6/3.6.12/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
